export type TPaletteTokens =
  | 'primary'
  | 'primaryDark'
  | 'secondary'
  | 'secondaryDark'
  | 'tertiary'
  | 'tertiaryDark'
  | 'errorRed'
  | 'successGreen'
  | 'warningOrange'
  | 'errorRedDark'
  | 'successGreenDark'
  | 'warningOrangeDark'
  | 'linkPurpleLight'
  | 'linkPurpleDark'
  | 'neutral1Light'
  | 'neutral1Dark'
  | 'highContrast1'

export interface TPalette extends Partial<Record<TPaletteTokens, string>> {}
