import { KrTypographyTokens } from '../Types/KrTypography'

export const KRTYPOGRAPHY_TOKENS: KrTypographyTokens[] = [
  'displayBoldLarge',
  'displayBoldMedium',
  'displayBoldSmall',
  'displayBoldItalicLarge',
  'displayBoldItalicMedium',
  'displayBoldItalicSmall',
  'headingBoldExtraLarge',
  'headingBoldLarge',
  'headingBoldMedium',
  'headingBoldSmall',
  'headingBoldExtraSmall',
  'subheadingSemiboldLarge',
  'subheadingSemiboldDefault',
  'headingBoldItalicExtraLarge',
  'headingBoldItalicLarge',
  'headingBoldItalicMedium',
  'headingBoldItalicSmall',
  'headingBoldItalicExtraSmall',
  'bodyRegularLarge',
  'bodyRegularMedium',
  'bodyRegularSmall',
  'bodyBoldLarge',
  'bodyBoldMedium',
  'bodyBoldSmall',
  'supportRegularInfo',
  'supportRegularFootnote',
  'supportBoldTextButton',
  'supportRegularMetadata',
]
